[build]
  command = "yarn run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "8"
  YARN_VERSION = "1.7.0"
  YARN_FLAGS = "--frozen-lockfile"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "ALLOW-FROM https://platform.twitter.com"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000"
    Content-Security-Policy = "default-src 'none'; object-src 'self' https://c.sharethis.mgr.consensu.org; img-src 'self' 'unsafe-inline' https://www.google-analytics.com https://stats.g.doubleclick.net https://l.sharethis.com data:; script-src 'self' 'unsafe-inline' https://www.google-analytics.com https://platform.twitter.com https://platform-api.sharethis.com https://buttons-config.sharethis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://assets-cdn.github.com; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com data:; frame-src 'self' https://c.sharethis.mgr.consensu.org/ https://platform.twitter.com https://syndication.twitter.com; connect-src 'self' https://www.google.com https://www.google-analytics.com https://fonts.googleapis.com https://fonts.gstatic.com https://stats.g.doubleclick.net https://platform.twitter.com https://syndication.twitter.com https://c.sharethis.mgr.consensu.org https://buttons-config.sharethis.com https://l.sharethis.com https://assets-cdn.github.com https://platform-api.sharethis.com; base-uri 'self'; form-action 'self' https://platform.twitter.com https://syndication.twitter.com; frame-ancestors 'self' https://platform.twitter.com https://syndication.twitter.com; manifest-src 'self'; prefetch-src 'self';"

[[redirects]]
  from = "https://weirdpattern.netlify.com/*"
  to = "https://www.weirdpattern.com/:splat"
  status = 301
  force = true
